// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/calculate": {
            "post": {
                "description": "执行各种类型的科学计算（原始版本）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "科学计算"
                ],
                "summary": "执行科学计算",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID，用于保持计算参数一致性，不传则自动生成",
                        "name": "session_id",
                        "in": "query"
                    },
                    {
                        "description": "计算请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CalculationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/calculate-fixed": {
            "post": {
                "description": "执行各种类型的科学计算（修复版），修正了ODE求解器的数值计算错误，返回严格符合数学要求的计算结果",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "科学计算"
                ],
                "summary": "执行科学计算（修复版）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID，用于保持计算参数一致性，不传则自动生成",
                        "name": "session_id",
                        "in": "query"
                    },
                    {
                        "description": "计算请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CalculationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/calculator-info": {
            "get": {
                "description": "获取指定计算器的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "计算器管理"
                ],
                "summary": "获取计算器信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "计算类型: solar_term, ganzhi, astronomy, starting_age, lunar, planet, star, sunrise_sunset, moon_phase, equation_solver",
                        "name": "calculation",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CalculatorInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "健康检查接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/solver/compare": {
            "post": {
                "description": "同时执行原始版和修复版计算，返回字段级的差异对比，用于验证修复效果",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "科学计算"
                ],
                "summary": "对比原始版与修复版求解器",
                "parameters": [
                    {
                        "description": "计算请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CalculationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CompareResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/supported-calculations": {
            "get": {
                "description": "获取系统支持的所有计算类型列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "计算器管理"
                ],
                "summary": "获取支持的计算类型",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/system-info": {
            "get": {
                "description": "获取系统支持的完整信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "获取系统信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SystemInfoResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CalculationResponse": {
            "type": "object",
            "properties": {
                "calculation": {
                    "type": "string"
                },
                "result": {},
                "session_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.CalculatorInfoResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.CompareResponse": {
            "type": "object",
            "properties": {
                "calculation": {
                    "type": "string"
                },
                "differences": {
                    "type": "object",
                    "additionalProperties": true
                },
                "fixed": {},
                "improvements": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "original": {},
                "session_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "summary": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "build_time": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "time": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "api.SystemInfoResponse": {
            "type": "object",
            "properties": {
                "supported_calculations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_calculators": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.CalculationRequest": {
            "type": "object",
            "required": [
                "calculation"
            ],
            "properties": {
                "calculation": {
                    "description": "计算类型",
                    "type": "string",
                    "example": "equation_solver"
                },
                "day": {
                    "description": "日期",
                    "type": "integer"
                },
                "days_from_term": {
                    "description": "距节气天数",
                    "type": "integer"
                },
                "hour": {
                    "description": "小时",
                    "type": "integer"
                },
                "minute": {
                    "description": "分钟",
                    "type": "integer"
                },
                "month": {
                    "description": "月份",
                    "type": "integer"
                },
                "params": {
                    "description": "计算参数（格式1）"
                },
                "second": {
                    "description": "秒",
                    "type": "integer"
                },
                "solar_date": {
                    "description": "阳历日期",
                    "type": "string"
                },
                "target_longitude": {
                    "description": "目标黄经",
                    "type": "number"
                },
                "term_index": {
                    "description": "节气索引 (0-23)",
                    "type": "integer"
                },
                "year": {
                    "description": "直接参数（格式2）",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "科学计算工具集 API",
	Description:      "功能丰富的Go语言科学计算库，提供天文计算、历法转换、方程求解等多种科学计算功能。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
