// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/calculate": {
            "post": {
                "description": "执行各种类型的科学计算",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "科学计算"
                ],
                "summary": "执行科学计算",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID，用于保持计算参数一致性，不传则自动生成",
                        "name": "session_id",
                        "in": "query"
                    },
                    {
                        "description": "计算请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CalculationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/calculate-fixed": {
            "post": {
                "description": "执行各种类型的科学计算（修复版）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "科学计算"
                ],
                "summary": "执行修复版科学计算",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID，用于保持计算参数一致性，不传则自动生成",
                        "name": "session_id",
                        "in": "query"
                    },
                    {
                        "description": "计算请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CalculationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CalculationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/calculator-info": {
            "get": {
                "description": "获取指定计算器的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "计算器管理"
                ],
                "summary": "获取计算器信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "计算类型: solar_term, ganzhi, astronomy, starting_age, lunar, planet, star, sunrise_sunset, moon_phase",
                        "name": "calculation",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CalculatorInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "健康检查接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/solver/compare": {
            "post": {
                "description": "对比新旧方程求解器的计算结果差异",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "科学计算"
                ],
                "summary": "对比新旧求解器",
                "parameters": [
                    {
                        "description": "计算请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CalculationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SolverComparisonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/system-info": {
            "get": {
                "description": "获取系统支持的完整信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "获取系统信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SystemInfoResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CalculationResponse": {
            "type": "object",
            "properties": {
                "calculation": {
                    "type": "string"
                },
                "result": {},
                "session_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.CalculatorInfoResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "api.FieldDiff": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "difference": {
                    "type": "number"
                },
                "field": {
                    "type": "string"
                },
                "new_value": {},
                "old_value": {}
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "build_time": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "time": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "api.SolverComparisonReport": {
            "type": "object",
            "properties": {
                "converged_new": {
                    "type": "boolean"
                },
                "converged_old": {
                    "type": "boolean"
                },
                "error_new_vs_old": {
                    "type": "number"
                },
                "error_new_vs_theory": {
                    "type": "number"
                },
                "error_old_vs_theory": {
                    "type": "number"
                },
                "field_differences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.FieldDiff"
                    }
                },
                "final_value_new": {
                    "type": "number"
                },
                "final_value_old": {
                    "type": "number"
                },
                "final_value_theory": {
                    "type": "number"
                },
                "improvement_ratio": {
                    "type": "number"
                },
                "initial_value": {
                    "type": "number"
                },
                "issue_summary": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "iterations_new": {
                    "type": "integer"
                },
                "iterations_old": {
                    "type": "integer"
                },
                "max_error_new": {
                    "type": "number"
                },
                "max_error_old": {
                    "type": "number"
                },
                "mean_error_new": {
                    "type": "number"
                },
                "mean_error_old": {
                    "type": "number"
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "test_equation": {
                    "type": "string"
                },
                "time_points_match": {
                    "type": "boolean"
                },
                "time_range": {
                    "type": "number"
                },
                "time_step": {
                    "type": "number"
                }
            }
        },
        "api.SolverComparisonResponse": {
            "type": "object",
            "properties": {
                "calculation": {
                    "type": "string"
                },
                "comparison_report": {
                    "$ref": "#/definitions/api.SolverComparisonReport"
                },
                "new_result": {},
                "old_result": {},
                "session_id": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "api.SystemInfoResponse": {
            "type": "object",
            "properties": {
                "supported_calculations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_calculators": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.CalculationRequest": {
            "type": "object",
            "required": [
                "calculation"
            ],
            "properties": {
                "calculation": {
                    "description": "璁＄畻绫诲瀷",
                    "type": "string"
                },
                "day": {
                    "description": "鏃ユ湡",
                    "type": "integer"
                },
                "days_from_term": {
                    "description": "璺濊妭姘斿ぉ鏁?",
                    "type": "integer"
                },
                "hour": {
                    "description": "灏忔椂",
                    "type": "integer"
                },
                "minute": {
                    "description": "鍒嗛挓",
                    "type": "integer"
                },
                "month": {
                    "description": "鏈堜唤",
                    "type": "integer"
                },
                "params": {
                    "description": "璁＄畻鍙傛暟锛堟牸寮?锛?"
                },
                "second": {
                    "description": "绉?",
                    "type": "integer"
                },
                "solar_date": {
                    "description": "闃冲巻鏃ユ湡",
                    "type": "string"
                },
                "target_longitude": {
                    "description": "鐩爣榛勭粡",
                    "type": "number"
                },
                "term_index": {
                    "description": "鑺傛皵绱㈠紩 (0-23)",
                    "type": "integer"
                },
                "year": {
                    "description": "鐩存帴鍙傛暟锛堟牸寮?锛?",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "科学计算工具集 API",
	Description:      "功能丰富的Go语言科学计算库，提供天文计算、历法转换、方程求解等多种科学计算功能。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
